# Base URL
@baseUrl = http://localhost:3000

### Tester la route /generate
POST {{baseUrl}}/generate
Content-Type: application/json

{
}

### Tester la route /export
POST {{baseUrl}}/export
Content-Type: application/json

{
  "data": [{
      
    }
  ],
  "format": "csv"
}


### Tester la route /logs
GET {{baseUrl}}/logs
Content-Type: application/json

{
}

